# Generated by Django 4.2.3 on 2023-07-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0009_bloque_imagen_alter_bloque_numero_planta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Sitio'),
        ),
    ]
