# Generated by Django 4.2.3 on 2023-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0010_sitio_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitio',
            name='foto',
        ),
        migrations.AddField(
            model_name='sitio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bloque_imagenes/'),
        ),
    ]
