# Generated by Django 4.2.3 on 2023-07-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0011_remove_sitio_foto_sitio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='nombre_director',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Director'),
        ),
    ]
