# Generated by Django 4.2.3 on 2023-07-31 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0012_sitio_nombre_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitio',
            old_name='imagen',
            new_name='foto',
        ),
    ]
