# Generated by Django 4.2.2 on 2023-07-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrador", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suscriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
