# Generated by Django 4.2.2 on 2023-07-25 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrador", "0003_usuario_delete_suscriptor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usuario",
            new_name="Suscriptor",
        ),
    ]
