# Generated by Django 4.2.3 on 2023-07-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_suscriptor_delete_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscriptor',
        ),
    ]
